### ISSUE TITLE
invalid subjects panics the server when adding a stream

### ISSUE THREAD

**Issue by ripienaar** [nats-io/jetstream#144]
If someone sends `foo.bar.` as a subject when creating a stream the server panics. 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14a210c]

goroutine 118 [running]:
github.com/nats-io/nats-server/v2/server.(*Stream).subscribeInternal(0xc0000c0000, 0xc0000d2100, 0xc, 0xc000286150, 0xc0000ba8f8, 0x8, 0x4080900)
        /Users/rip/go/pkg/mod/github.com/nats-io/nats-server/v2@v2.1.5-0.20200408210822-8d49c8038859/server/stream.go:385 +0x18c
github.com/nats-io/nats-server/v2/server.(*Stream).subscribeToStream(0xc0000c0000, 0xc0000baa28, 0x0)
        /Users/rip/go/pkg/mod/github.com/nats-io/nats-server/v2@v2.1.5-0.20200408210822-8d49c8038859/server/stream.go:350 +0xd2
github.com/nats-io/nats-server/v2/server.(*Account).AddStreamWithStore(0xc00014c000, 0xc000288100, 0x0, 0xc000118201, 0xc, 0x0)
        /Users/rip/go/pkg/mod/github.com/nats-io/nats-server/v2@v2.1.5-0.20200408210822-8d49c8038859/server/stream.go:135 +0x44c
github.com/nats-io/nats-server/v2/server.(*Account).AddStream(...)
        /Users/rip/go/pkg/mod/github.com/nats-io/nats-server/v2@v2.1.5-0.20200408210822-8d49c8038859/server/stream.go:69
github.com/nats-io/nats-server/v2/server.(*Server).jsCreateStreamRequest(0xc000130000, 0xc0002d3560, 0xc0002bcc80, 0xc000118240, 0x1e, 0xc000242120, 0x26, 0xc003f0a477, 0xc8, 0x189)
        /Users/rip/go/pkg/mod/github.com/nats-io/nats-server/v2@v2.1.5-0.20200408210822-8d49c8038859/server/jetstream_api.go:374 +0x241
github.com/nats-io/nats-server/v2/server.(*client).deliverMsg(0xc0002bcc80, 0xc0002d3560, 0xc0001f9378, 0x1e, 0x20, 0xc0002bcf69, 0x3d, 0x3ff, 0xc003f0a477, 0xca, ...)
        /Users/rip/go/pkg/mod/github.com/nats-io/nats-server/v2@v2.1.5-0.20200408210822-8d49c8038859/server/client.go:2501 +0x2f4
github.com/nats-io/nats-server/v2/server.(*client).processMsgResults(0xc0002bcc80, 0xc0002b4000, 0xc00010b2c0, 0xc003f0a477, 0xca, 0x189, 0x0, 0x0, 0x0, 0xc0000bb378, ...)
        /Users/rip/go/pkg/mod/github.com/nats-io/nats-server/v2@v2.1.5-0.20200408210822-8d49c8038859/server/client.go:3148 +0x720
github.com/nats-io/nats-server/v2/server.(*client).processServiceImport(0xc0002bcc80, 0xc000281200, 0xc00014c000, 0xc003f0a477, 0xca, 0x189)
        /Users/rip/go/pkg/mod/github.com/nats-io/nats-server/v2@v2.1.5-0.20200408210822-8d49c8038859/server/client.go:3014 +0x5ee
github.com/nats-io/nats-server/v2/server.(*Account).addServiceImportSub.func1(0xc0002e0ab0, 0xc0002bcc80, 0xc000118160, 0x1e, 0xc0002420c0, 0x26, 0xc003f0a477, 0xca, 0x189)
        /Users/rip/go/pkg/mod/github.com/nats-io/nats-server/v2@v2.1.5-0.20200408210822-8d49c8038859/server/accounts.go:1047 +0x5e
github.com/nats-io/nats-server/v2/server.(*client).deliverMsg(0xc0002bcc80, 0xc0002e0ab0, 0xc003f0a42c, 0x1e, 0x1d4, 0xc0002bcf69, 0x51, 0x3ff, 0xc003f0a477, 0xca, ...)
        /Users/rip/go/pkg/mod/github.com/nats-io/nats-server/v2@v2.1.5-0.20200408210822-8d49c8038859/server/client.go:2499 +0x3fa
github.com/nats-io/nats-server/v2/server.(*client).processMsgResults(0xc0002bcc80, 0xc00014c000, 0xc00010b1d0, 0xc003f0a477, 0xca, 0x189, 0x0, 0x0, 0x0, 0xc003f0a42c, ...)
        /Users/rip/go/pkg/mod/github.com/nats-io/nats-server/v2@v2.1.5-0.20200408210822-8d49c8038859/server/client.go:3148 +0x720
github.com/nats-io/nats-server/v2/server.(*client).processInboundClientMsg(0xc0002bcc80, 0xc003f0a477, 0xca, 0x189, 0x18e)
        /Users/rip/go/pkg/mod/github.com/nats-io/nats-server/v2@v2.1.5-0.20200408210822-8d49c8038859/server/client.go:2874 +0x520
github.com/nats-io/nats-server/v2/server.(*client).processInboundMsg(0xc0002bcc80, 0xc003f0a477, 0xca, 0x189)
        /Users/rip/go/pkg/mod/github.com/nats-io/nats-server/v2@v2.1.5-0.20200408210822-8d49c8038859/server/client.go:2753 +0x95
github.com/nats-io/nats-server/v2/server.(*client).parse(0xc0002bcc80, 0xc003f0a400, 0x141, 0x200, 0x141, 0x0)
        /Users/rip/go/pkg/mod/github.com/nats-io/nats-server/v2@v2.1.5-0.20200408210822-8d49c8038859/server/parser.go:288 +0x17dc
github.com/nats-io/nats-server/v2/server.(*client).readLoop(0xc0002bcc80)
        /Users/rip/go/pkg/mod/github.com/nats-io/nats-server/v2@v2.1.5-0.20200408210822-8d49c8038859/server/client.go:907 +0x333
github.com/nats-io/nats-server/v2/server.(*Server).createClient.func2()
        /Users/rip/go/pkg/mod/github.com/nats-io/nats-server/v2@v2.1.5-0.20200408210822-8d49c8038859/server/server.go:1896 +0x2a
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine
        /Users/rip/go/pkg/mod/github.com/nats-io/nats-server/v2@v2.1.5-0.20200408210822-8d49c8038859/server/server.go:2252 +0xad
```

**Comment by derekcollison** [comment]
ok will fix.
