### ISSUE TITLE
Crash when doing stream commands from cli

### ISSUE THREAD

**Issue by jbresson** [nats-io/jetstream#437]
using current master freshly built version of natscli and `synadia/nats-server:nightly-20210127` image.
`natscli str info test`
or many other stream calls besides `ls` cause a crash. the above command got this panic log:
```
natscli call attempt ->
nats-0 nats panic: runtime error: invalid memory address or nil pointer dereference
nats-0 nats [signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x8d011a]
nats-0 nats 
nats-0 nats goroutine 94 [running]:
nats-0 nats github.com/nats-io/nats-server/server.(*jetStreamCluster).isStreamLeader(0xc0000a2900, 0xb18bd6, 0x2, 0xc000525af4, 0x7, 0x0)
nats-0 nats 	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:562 +0x15a
nats-0 nats github.com/nats-io/nats-server/server.(*Account).JetStreamIsStreamLeader(0xc00015a000, 0xc000525af4, 0x7, 0x0)
nats-0 nats 	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:358 +0xd1
nats-0 nats github.com/nats-io/nats-server/server.(*Server).jsStreamInfoRequest(0xc000137500, 0xc0000e9e40, 0xc000688c80, 0xc000525ae0, 0x1b, 0xc000525b00, 0x11, 0xc000638140, 0xd2, 0x131)
nats-0 nats 	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/jetstream_api.go:1132 +0xc3a
nats-0 nats github.com/nats-io/nats-server/server.(*client).deliverMsg(0xc000688c80, 0xc0000e9e40, 0xc00008d0d0, 0x1b, 0x20, 0xc000525aa0, 0x11, 0x20, 0xc00068a0e8, 0x3f, ...)
nats-0 nats 	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/client.go:3016 +0x36f
nats-0 nats github.com/nats-io/nats-server/server.(*client).processMsgResults(0xc000688c80, 0xc0000be000, 0xc000314060, 0xc000638140, 0xd4, 0x131, 0x0, 0x0, 0x0, 0xc0006410d0, ...)
nats-0 nats 	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/client.go:3874 +0x62b
nats-0 nats github.com/nats-io/nats-server/server.(*client).processServiceImport(0xc000688c80, 0xc00030cb40, 0xc00015a000, 0xc000638140, 0xd4, 0x131)
nats-0 nats 	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/client.go:3695 +0xa25
nats-0 nats github.com/nats-io/nats-server/server.(*Account).addServiceImportSub.func1(0xc000300fd0, 0xc000688c80, 0xc000525a40, 0x1b, 0xc0000bc210, 0x26, 0xc00056464a, 0x2, 0x1b6)
nats-0 nats 	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/accounts.go:1796 +0x5e
nats-0 nats github.com/nats-io/nats-server/server.(*client).deliverMsg(0xc000688c80, 0xc000300fd0, 0xc000564604, 0x1b, 0x1fc, 0xc000564620, 0x26, 0x1e0, 0xc00068a0e9, 0x4d, ...)
nats-0 nats 	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/client.go:3014 +0x47d
nats-0 nats github.com/nats-io/nats-server/server.(*client).processMsgResults(0xc000688c80, 0xc00015a000, 0xc000314000, 0xc00056464a, 0x2, 0x1b6, 0x0, 0x0, 0x0, 0xc000564604, ...)
nats-0 nats 	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/client.go:3874 +0x62b
nats-0 nats github.com/nats-io/nats-server/server.(*client).processInboundClientMsg(0xc000688c80, 0xc00056464a, 0x2, 0x1b6, 0x1b9)
nats-0 nats 	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/client.go:3449 +0x3be
nats-0 nats github.com/nats-io/nats-server/server.(*client).processInboundMsg(0xc000688c80, 0xc00056464a, 0x2, 0x1b6)
nats-0 nats 	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/client.go:3315 +0x95
nats-0 nats github.com/nats-io/nats-server/server.(*client).parse(0xc000688c80, 0xc000564600, 0x4c, 0x200, 0x4c, 0x0)
nats-0 nats 	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/parser.go:477 +0x26fb
nats-0 nats github.com/nats-io/nats-server/server.(*client).readLoop(0xc000688c80, 0x0, 0x0, 0x0)
nats-0 nats 	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/client.go:1093 +0x545
nats-0 nats github.com/nats-io/nats-server/server.(*Server).createClient.func2()
nats-0 nats 	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/server.go:2324 +0x45
nats-0 nats created by github.com/nats-io/nats-server/server.(*Server).startGoRoutine
```

**Comment by ripienaar** [comment]
FYI @derekcollison

**Comment by derekcollison** [comment]
I have not been able to reproduce this with the latest nightly.

**Comment by ripienaar** [comment]
yeah ditto, probably fixed as a side effect of the many other fixes we did, lets close this one
